### ISSUE TITLE
Plotting of relevant data from AMP-AD

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/WallOfTargetsShiny#11]
Histogram/Line Plot/Bar Plot.  Experiment and see what looks best.  Define baseline value of data so it is intuitive what you are comparing the data to.

**Comment by blogsdon** [comment]
expression values to depict disease specific differences in expression of genes in the local neighborhood of the target - I will get Kenny expression and diagnosis values

**Comment by kdaily** [comment]
little confused as to what to get from the covariates - using `cogdx` now, but it's a bit jumbled, especially with multiple genes selected.

**Comment by blogsdon** [comment]
Use cogdx.  Subset by cogdx of 1 vs cogdx of 4.

**Comment by kdaily** [comment]
Confirmed!

**Comment by kdaily** [comment]
Fixed by #24.
