### ISSUE TITLE
Add four modules for target dashboard

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/WallOfTargetsShiny#12]
- [x] 1. Module 1 - AMP-AD evidence (genetics/networks)
- [x] 2. Module 2 - Druggability (also potentially Pharos, but primarily ODDI custom data)
- [x] 3. Module 3 - Tissue specific gene and protein expression patterns of gene - GTEx
- [x] 4. Module 4 - Assays and models available for a given target - (ODDI provided data as well)

**Comment by blogsdon** [comment]
@th1vairam do you know where the processed GTeX data is on Synapse?

**Comment by kdaily** [comment]
For Module 2/4, from `DDI medium list.xlsx`:

Use Gene name, cols E-I map color to status (red, green, orange, unknown/grey) - E-G are in module 2, H-I are in module 4.

Maybe an aggregate sum score for each module?

**Comment by kdaily** [comment]
For `Pioneer targets Lilly drugabillity.xlsx` just column D (module 2)

**Comment by kdaily** [comment]
Finished, except for aggregate score. Closing here, reopening as another issue.
