### ISSUE TITLE
Differential expression at gene level widget

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/WallOfTargetsShiny#67]

**Comment by kdaily** [comment]
A forest plot of effect estimates for set of genes as a fxn of brain region/disease?

**Comment by kdaily** [comment]
volcano plot, per brain region/study?

**Comment by kdaily** [comment]
table/summary of expression levels as fxn of disease status

**Comment by kdaily** [comment]
Using these datasets of summary statistics:

- syn8468023 (mayo)
- syn10157628 (msbb)
- syn8456721 (rosmap)

**Comment by kdaily** [comment]
Unsure about what set of columns is required for uniqueness, looks like:

```
Model, Comparison, BrainRegion.ref, BrainRegion.ag, Gender.ref, Gender.ag, AOD.ref, AOD.ag, ensembl_gene_id, hgnc_symbol, logFC, CI.L, CI.R, AveExpr, adj.P.Val
```

But MSBB and ROSMAP do not have `BrainRegion.ref` and `BrainRegion.ag` columns.

**Comment by blogsdon** [comment]
@th1vairam is the person to answer this question

**Comment by th1vairam** [comment]
Here is a merged table from all three studies, 4 models with 7 brain regions and 4 comparisons https://www.synapse.org/#!Synapse:syn11180450

**Comment by th1vairam** [comment]
This is the code I used to do the above merge https://github.com/th1vairam/Brain_Reg_Net/blob/AMPAD_reprocessing/code/R/collateDifferentialExpressionResults.R

**Comment by kdaily** [comment]
Done.
